# Generated by Django 5.2.2 on 2025-06-28 09:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گروه')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه ها',
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تخصص')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise_group', to='section.group', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'تخصص ها',
            },
        ),
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', upload_to='excels/', verbose_name='فایل اکسل')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_group', to='section.group', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'اکسل',
                'verbose_name_plural': 'اکسل ها',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_manager', models.BooleanField(default=True, verbose_name='دسترسی مسئول')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_group', to='section.group', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'اکانت',
                'verbose_name_plural': 'اکانت\u200c ها',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام اتاق عمل')),
                ('sheet', models.CharField(blank=True, max_length=100, null=True, verbose_name='برگ اتاق عمل')),
                ('expertises', models.ManyToManyField(blank=True, related_name='room_expertises', to='section.expertise', verbose_name='تخصص ها')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_group', to='section.group', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'اتاق عمل',
                'verbose_name_plural': 'اتاق های عمل',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='نام و نام خانوادگی')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_group', to='section.group', verbose_name='گروه')),
                ('rooms', models.ManyToManyField(blank=True, related_name='patient_rooms', to='section.room', verbose_name='اتاق های عمل')),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیماران',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('grade', models.CharField(blank=True, choices=[('1', 'عمومی'), ('2', 'متخصص'), ('3', 'فوق تخصص')], max_length=1, null=True, verbose_name='درجه')),
                ('personnel_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پرسنلی')),
                ('expertises', models.ManyToManyField(blank=True, related_name='doctor_expertises', to='section.expertise', verbose_name='تخصص ها')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_group', to='section.group', verbose_name='گروه')),
                ('rooms', models.ManyToManyField(blank=True, related_name='doctor_rooms', to='section.room', verbose_name='اتاق های عمل')),
            ],
            options={
                'verbose_name': 'پزشک',
                'verbose_name_plural': 'پزشکان',
            },
        ),
        migrations.CreateModel(
            name='RoomCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalization_date', models.CharField(max_length=10, verbose_name='تاریخ بستری')),
                ('discharge_date', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ ترخیص')),
                ('operation_date', models.CharField(max_length=10, verbose_name='تاریخ عمل')),
                ('number', models.CharField(max_length=50, verbose_name='شماره پرونده')),
                ('operation_type', models.CharField(blank=True, choices=[('1', 'عمل کوچک'), ('2', 'عمل متوسط'), ('3', 'عمل بزرگ')], max_length=1, null=True, verbose_name='نوع جراحی')),
                ('k', models.IntegerField(verbose_name='کا')),
                ('anesthesia_type', models.CharField(blank=True, choices=[('1', 'موضعی'), ('2', 'غیر موضعی')], max_length=1, null=True, verbose_name='نوع بیهوشی')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_room_case', to='section.doctor', verbose_name='جراح')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_case_group', to='section.group', verbose_name='گروه')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_room_case', to='section.patient', verbose_name='بیمار')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_case', to='section.room', verbose_name='اتاق عمل')),
            ],
            options={
                'verbose_name': 'پرونده اتاق عمل',
                'verbose_name_plural': 'پرونده های اتاق عمل',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام بخش')),
                ('sheet', models.CharField(blank=True, max_length=100, null=True, verbose_name='برگ بخش')),
                ('expertises', models.ManyToManyField(blank=True, related_name='section_expertises', to='section.expertise', verbose_name='تخصص ها')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_group', to='section.group', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'بخش',
                'verbose_name_plural': 'بخش ها',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='patient_sections', to='section.section', verbose_name='بخش ها'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='doctor_sections', to='section.section', verbose_name='بخش ها'),
        ),
        migrations.CreateModel(
            name='DC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='شماره پرونده')),
                ('cause_of_death', models.CharField(blank=True, max_length=100, null=True, verbose_name='علت فوت')),
                ('location_of_death', models.CharField(blank=True, max_length=100, null=True, verbose_name='بخش محل فوت')),
                ('death_date', models.CharField(max_length=10, verbose_name='تاریخ فوت')),
                ('admission_date', models.CharField(max_length=10, verbose_name='تاریخ پذیرش')),
                ('age', models.CharField(max_length=3, verbose_name='سن بیمار')),
                ('gender', models.CharField(choices=[('1', 'مرد'), ('2', 'زن')], max_length=1, verbose_name='جنسیت')),
                ('delivery_date', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ تحویل')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_dc', to='section.doctor', verbose_name='پزشک')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_group', to='section.group', verbose_name='گروه')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_dc', to='section.patient', verbose_name='بیمار')),
                ('hospitalization_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_dc', to='section.section', verbose_name='بخش بستری')),
            ],
            options={
                'verbose_name': 'پرونده فوت',
                'verbose_name_plural': 'پرونده های فوت',
            },
        ),
        migrations.CreateModel(
            name='SectionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance', models.CharField(blank=True, max_length=100, null=True, verbose_name='بیمه')),
                ('discharge_date', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ ترخیص')),
                ('admission_date', models.CharField(max_length=10, verbose_name='تاریخ پذیرش')),
                ('number', models.CharField(max_length=50, verbose_name='شماره پرونده')),
                ('delivery_date', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ تحویل')),
                ('defect_sheet', models.CharField(blank=True, choices=[('1', 'برگ پذیرش خلاصه ترخیص'), ('2', 'برگ خلاصه پرونده'), ('3', 'برگ شرح حال'), ('4', 'برگ سیربیماری'), ('5', 'برگ مشاوره'), ('6', 'برگ مراقبت قبل از عمل'), ('7', 'برگ بیهوشی'), ('8', 'برگ شرح عمل'), ('9', 'برگ مراقبت بعد از عمل'), ('10', 'دستورات پزشک'), ('11', 'گزارش پرستار'), ('12', 'نمودار علائم حیاتی'), ('13', 'رضایت آگاهانه'), ('14', 'صورتحساب'), ('15', 'چک لیست')], max_length=2, null=True, verbose_name='برگ نقص')),
                ('defect_type', models.CharField(blank=True, choices=[('1', 'عدم درج مهر پزشک'), ('2', 'مهر مشاوره'), ('3', 'مهر tellorder'), ('4', 'فقدان برگ'), ('5', 'عدم تکمیل گزارش'), ('6', 'خط خوردگی'), ('7', 'عدم تکمیل سربرگ'), ('8', 'عدم تشخیص نویسی'), ('9', 'عدم اخذ رضایت'), ('10', 'عدم اثر انگشت و امضا'), ('11', 'عدم ثبت دقیق آدرس و تلفن بیمار')], max_length=2, null=True, verbose_name='نوع نقص')),
                ('defect_sheet2', models.CharField(blank=True, choices=[('1', 'برگ پذیرش خلاصه ترخیص'), ('2', 'برگ خلاصه پرونده'), ('3', 'برگ شرح حال'), ('4', 'برگ سیربیماری'), ('5', 'برگ مشاوره'), ('6', 'برگ مراقبت قبل از عمل'), ('7', 'برگ بیهوشی'), ('8', 'برگ شرح عمل'), ('9', 'برگ مراقبت بعد از عمل'), ('10', 'دستورات پزشک'), ('11', 'گزارش پرستار'), ('12', 'نمودار علائم حیاتی'), ('13', 'رضایت آگاهانه'), ('14', 'صورتحساب'), ('15', 'چک لیست')], max_length=2, null=True, verbose_name='2 برگ نقص')),
                ('defect_type2', models.CharField(blank=True, choices=[('1', 'عدم درج مهر پزشک'), ('2', 'مهر مشاوره'), ('3', 'مهر tellorder'), ('4', 'فقدان برگ'), ('5', 'عدم تکمیل گزارش'), ('6', 'خط خوردگی'), ('7', 'عدم تکمیل سربرگ'), ('8', 'عدم تشخیص نویسی'), ('9', 'عدم اخذ رضایت'), ('10', 'عدم اثر انگشت و امضا'), ('11', 'عدم ثبت دقیق آدرس و تلفن بیمار')], max_length=2, null=True, verbose_name='2 نوع نقص')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_case', to='section.doctor', verbose_name='پزشک')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_case_group', to='section.group', verbose_name='گروه')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_case', to='section.patient', verbose_name='بیمار')),
                ('representative_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_doctor_case', to='section.doctor', verbose_name='پزشک معرف')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_case', to='section.section', verbose_name='بخش')),
            ],
            options={
                'verbose_name': 'پرونده بخش',
                'verbose_name_plural': 'پرونده های بخش',
            },
        ),
    ]
