# Generated by Django 5.2.2 on 2025-06-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_alter_customuser_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcase',
            name='anesthesia_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع بیهوشی'),
        ),
        migrations.AlterField(
            model_name='roomcase',
            name='k',
            field=models.CharField(max_length=10, verbose_name='کا'),
        ),
    ]
