# Generated by Django 5.2.2 on 2025-07-08 08:53

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_alter_roomcase_anesthesia_type_alter_roomcase_k'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncase',
            name='defect_sheet10',
            field=models.CharField(blank=True, choices=[('1', 'برگ پذیرش خلاصه ترخیص'), ('2', 'برگ خلاصه پرونده'), ('3', 'برگ شرح حال'), ('4', 'برگ سیربیماری'), ('5', 'برگ مشاوره'), ('6', 'برگ مراقبت قبل از عمل'), ('7', 'برگ بیهوشی'), ('8', 'برگ شرح عمل'), ('9', 'برگ مراقبت بعد از عمل'), ('10', 'دستورات پزشک'), ('11', 'گزارش پرستار'), ('12', 'نمودار علائم حیاتی'), ('13', 'رضایت آگاهانه'), ('14', 'صورتحساب'), ('15', 'چک لیست')], max_length=2, null=True, verbose_name='10 برگ نقص'),
        ),
        migrations.AddField(
            model_name='sectioncase',
            name='defect_sheet3',
            field=models.CharField(blank=True, choices=[('1', 'برگ پذیرش خلاصه ترخیص'), ('2', 'برگ خلاصه پرونده'), ('3', 'برگ شرح حال'), ('4', 'برگ سیربیماری'), ('5', 'برگ مشاوره'), ('6', 'برگ مراقبت قبل از عمل'), ('7', 'برگ بیهوشی'), ('8', 'برگ شرح عمل'), ('9', 'برگ مراقبت بعد از عمل'), ('10', 'دستورات پزشک'), ('11', 'گزارش پرستار'), ('12', 'نمودار علائم حیاتی'), ('13', 'رضایت آگاهانه'), ('14', 'صورتحساب'), ('15', 'چک لیست')], max_length=2, null=True, verbose_name='3 برگ نقص'),
        ),
        migrations.AddField(
            model_name='sectioncase',
            name='defect_sheet4',
            field=models.CharField(blank=True, choices=[('1', 'برگ پذیرش خلاصه ترخیص'), ('2', 'برگ خلاصه پرونده'), ('3', 'برگ شرح حال'), ('4', 'برگ سیربیماری'), ('5', 'برگ مشاوره'), ('6', 'برگ مراقبت قبل از عمل'), ('7', 'برگ بیهوشی'), ('8', 'برگ شرح عمل'), ('9', 'برگ مراقبت بعد از عمل'), ('10', 'دستورات پزشک'), ('11', 'گزارش پرستار'), ('12', 'نمودار علائم حیاتی'), ('13', 'رضایت آگاهانه'), ('14', 'صورتحساب'), ('15', 'چک لیست')], max_length=2, null=True, verbose_name='4 برگ نقص'),
        ),
        migrations.AddField(
            model_name='sectioncase',
            name='defect_sheet5',
            field=models.CharField(blank=True, choices=[('1', 'برگ پذیرش خلاصه ترخیص'), ('2', 'برگ خلاصه پرونده'), ('3', 'برگ شرح حال'), ('4', 'برگ سیربیماری'), ('5', 'برگ مشاوره'), ('6', 'برگ مراقبت قبل از عمل'), ('7', 'برگ بیهوشی'), ('8', 'برگ شرح عمل'), ('9', 'برگ مراقبت بعد از عمل'), ('10', 'دستورات پزشک'), ('11', 'گزارش پرستار'), ('12', 'نمودار علائم حیاتی'), ('13', 'رضایت آگاهانه'), ('14', 'صورتحساب'), ('15', 'چک لیست')], max_length=2, null=True, verbose_name='5 برگ نقص'),
        ),
        migrations.AddField(
            model_name='sectioncase',
            name='defect_sheet6',
            field=models.CharField(blank=True, choices=[('1', 'برگ پذیرش خلاصه ترخیص'), ('2', 'برگ خلاصه پرونده'), ('3', 'برگ شرح حال'), ('4', 'برگ سیربیماری'), ('5', 'برگ مشاوره'), ('6', 'برگ مراقبت قبل از عمل'), ('7', 'برگ بیهوشی'), ('8', 'برگ شرح عمل'), ('9', 'برگ مراقبت بعد از عمل'), ('10', 'دستورات پزشک'), ('11', 'گزارش پرستار'), ('12', 'نمودار علائم حیاتی'), ('13', 'رضایت آگاهانه'), ('14', 'صورتحساب'), ('15', 'چک لیست')], max_length=2, null=True, verbose_name='6 برگ نقص'),
        ),
        migrations.AddField(
            model_name='sectioncase',
            name='defect_sheet7',
            field=models.CharField(blank=True, choices=[('1', 'برگ پذیرش خلاصه ترخیص'), ('2', 'برگ خلاصه پرونده'), ('3', 'برگ شرح حال'), ('4', 'برگ سیربیماری'), ('5', 'برگ مشاوره'), ('6', 'برگ مراقبت قبل از عمل'), ('7', 'برگ بیهوشی'), ('8', 'برگ شرح عمل'), ('9', 'برگ مراقبت بعد از عمل'), ('10', 'دستورات پزشک'), ('11', 'گزارش پرستار'), ('12', 'نمودار علائم حیاتی'), ('13', 'رضایت آگاهانه'), ('14', 'صورتحساب'), ('15', 'چک لیست')], max_length=2, null=True, verbose_name='7 برگ نقص'),
        ),
        migrations.AddField(
            model_name='sectioncase',
            name='defect_sheet8',
            field=models.CharField(blank=True, choices=[('1', 'برگ پذیرش خلاصه ترخیص'), ('2', 'برگ خلاصه پرونده'), ('3', 'برگ شرح حال'), ('4', 'برگ سیربیماری'), ('5', 'برگ مشاوره'), ('6', 'برگ مراقبت قبل از عمل'), ('7', 'برگ بیهوشی'), ('8', 'برگ شرح عمل'), ('9', 'برگ مراقبت بعد از عمل'), ('10', 'دستورات پزشک'), ('11', 'گزارش پرستار'), ('12', 'نمودار علائم حیاتی'), ('13', 'رضایت آگاهانه'), ('14', 'صورتحساب'), ('15', 'چک لیست')], max_length=2, null=True, verbose_name='8 برگ نقص'),
        ),
        migrations.AddField(
            model_name='sectioncase',
            name='defect_sheet9',
            field=models.CharField(blank=True, choices=[('1', 'برگ پذیرش خلاصه ترخیص'), ('2', 'برگ خلاصه پرونده'), ('3', 'برگ شرح حال'), ('4', 'برگ سیربیماری'), ('5', 'برگ مشاوره'), ('6', 'برگ مراقبت قبل از عمل'), ('7', 'برگ بیهوشی'), ('8', 'برگ شرح عمل'), ('9', 'برگ مراقبت بعد از عمل'), ('10', 'دستورات پزشک'), ('11', 'گزارش پرستار'), ('12', 'نمودار علائم حیاتی'), ('13', 'رضایت آگاهانه'), ('14', 'صورتحساب'), ('15', 'چک لیست')], max_length=2, null=True, verbose_name='9 برگ نقص'),
        ),
        migrations.AddField(
            model_name='sectioncase',
            name='defect_type10',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'عدم درج مهر پزشک'), ('2', 'مهر مشاوره'), ('3', 'مهر tellorder'), ('4', 'فقدان برگ'), ('5', 'عدم تکمیل گزارش'), ('6', 'خط خوردگی'), ('7', 'عدم تکمیل سربرگ'), ('8', 'عدم تشخیص نویسی'), ('9', 'عدم اخذ رضایت'), ('10', 'عدم اثر انگشت و امضا'), ('11', 'عدم ثبت دقیق آدرس و تلفن بیمار')], max_length=23, null=True, verbose_name='10 نوع نقص'),
        ),
        migrations.AddField(
            model_name='sectioncase',
            name='defect_type3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'عدم درج مهر پزشک'), ('2', 'مهر مشاوره'), ('3', 'مهر tellorder'), ('4', 'فقدان برگ'), ('5', 'عدم تکمیل گزارش'), ('6', 'خط خوردگی'), ('7', 'عدم تکمیل سربرگ'), ('8', 'عدم تشخیص نویسی'), ('9', 'عدم اخذ رضایت'), ('10', 'عدم اثر انگشت و امضا'), ('11', 'عدم ثبت دقیق آدرس و تلفن بیمار')], max_length=23, null=True, verbose_name='3 نوع نقص'),
        ),
        migrations.AddField(
            model_name='sectioncase',
            name='defect_type4',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'عدم درج مهر پزشک'), ('2', 'مهر مشاوره'), ('3', 'مهر tellorder'), ('4', 'فقدان برگ'), ('5', 'عدم تکمیل گزارش'), ('6', 'خط خوردگی'), ('7', 'عدم تکمیل سربرگ'), ('8', 'عدم تشخیص نویسی'), ('9', 'عدم اخذ رضایت'), ('10', 'عدم اثر انگشت و امضا'), ('11', 'عدم ثبت دقیق آدرس و تلفن بیمار')], max_length=23, null=True, verbose_name='4 نوع نقص'),
        ),
        migrations.AddField(
            model_name='sectioncase',
            name='defect_type5',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'عدم درج مهر پزشک'), ('2', 'مهر مشاوره'), ('3', 'مهر tellorder'), ('4', 'فقدان برگ'), ('5', 'عدم تکمیل گزارش'), ('6', 'خط خوردگی'), ('7', 'عدم تکمیل سربرگ'), ('8', 'عدم تشخیص نویسی'), ('9', 'عدم اخذ رضایت'), ('10', 'عدم اثر انگشت و امضا'), ('11', 'عدم ثبت دقیق آدرس و تلفن بیمار')], max_length=23, null=True, verbose_name='5 نوع نقص'),
        ),
        migrations.AddField(
            model_name='sectioncase',
            name='defect_type6',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'عدم درج مهر پزشک'), ('2', 'مهر مشاوره'), ('3', 'مهر tellorder'), ('4', 'فقدان برگ'), ('5', 'عدم تکمیل گزارش'), ('6', 'خط خوردگی'), ('7', 'عدم تکمیل سربرگ'), ('8', 'عدم تشخیص نویسی'), ('9', 'عدم اخذ رضایت'), ('10', 'عدم اثر انگشت و امضا'), ('11', 'عدم ثبت دقیق آدرس و تلفن بیمار')], max_length=23, null=True, verbose_name='6 نوع نقص'),
        ),
        migrations.AddField(
            model_name='sectioncase',
            name='defect_type7',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'عدم درج مهر پزشک'), ('2', 'مهر مشاوره'), ('3', 'مهر tellorder'), ('4', 'فقدان برگ'), ('5', 'عدم تکمیل گزارش'), ('6', 'خط خوردگی'), ('7', 'عدم تکمیل سربرگ'), ('8', 'عدم تشخیص نویسی'), ('9', 'عدم اخذ رضایت'), ('10', 'عدم اثر انگشت و امضا'), ('11', 'عدم ثبت دقیق آدرس و تلفن بیمار')], max_length=23, null=True, verbose_name='7 نوع نقص'),
        ),
        migrations.AddField(
            model_name='sectioncase',
            name='defect_type8',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'عدم درج مهر پزشک'), ('2', 'مهر مشاوره'), ('3', 'مهر tellorder'), ('4', 'فقدان برگ'), ('5', 'عدم تکمیل گزارش'), ('6', 'خط خوردگی'), ('7', 'عدم تکمیل سربرگ'), ('8', 'عدم تشخیص نویسی'), ('9', 'عدم اخذ رضایت'), ('10', 'عدم اثر انگشت و امضا'), ('11', 'عدم ثبت دقیق آدرس و تلفن بیمار')], max_length=23, null=True, verbose_name='8 نوع نقص'),
        ),
        migrations.AddField(
            model_name='sectioncase',
            name='defect_type9',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'عدم درج مهر پزشک'), ('2', 'مهر مشاوره'), ('3', 'مهر tellorder'), ('4', 'فقدان برگ'), ('5', 'عدم تکمیل گزارش'), ('6', 'خط خوردگی'), ('7', 'عدم تکمیل سربرگ'), ('8', 'عدم تشخیص نویسی'), ('9', 'عدم اخذ رضایت'), ('10', 'عدم اثر انگشت و امضا'), ('11', 'عدم ثبت دقیق آدرس و تلفن بیمار')], max_length=23, null=True, verbose_name='9 نوع نقص'),
        ),
        migrations.AlterField(
            model_name='sectioncase',
            name='defect_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'عدم درج مهر پزشک'), ('2', 'مهر مشاوره'), ('3', 'مهر tellorder'), ('4', 'فقدان برگ'), ('5', 'عدم تکمیل گزارش'), ('6', 'خط خوردگی'), ('7', 'عدم تکمیل سربرگ'), ('8', 'عدم تشخیص نویسی'), ('9', 'عدم اخذ رضایت'), ('10', 'عدم اثر انگشت و امضا'), ('11', 'عدم ثبت دقیق آدرس و تلفن بیمار')], max_length=23, null=True, verbose_name='نوع نقص'),
        ),
        migrations.AlterField(
            model_name='sectioncase',
            name='defect_type2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'عدم درج مهر پزشک'), ('2', 'مهر مشاوره'), ('3', 'مهر tellorder'), ('4', 'فقدان برگ'), ('5', 'عدم تکمیل گزارش'), ('6', 'خط خوردگی'), ('7', 'عدم تکمیل سربرگ'), ('8', 'عدم تشخیص نویسی'), ('9', 'عدم اخذ رضایت'), ('10', 'عدم اثر انگشت و امضا'), ('11', 'عدم ثبت دقیق آدرس و تلفن بیمار')], max_length=23, null=True, verbose_name='2 نوع نقص'),
        ),
    ]
